### ISSUE TITLE
Error occurred in poll cycle: end of file reached

### ISSUE THREAD

**Issue by praveenk0535** [easytaxibr/newrelic_activemq#3]
I am trying to setup monitoring for one of our ActiveMQ queuesI gave the required info in the config and when I run the plugin I am seeing the below error

Error occurred in poll cycle: end of file reached

Can you help with this?

**Comment by stupied4ever** [comment]
@praveenk0535 probably you already solved or aborted the use, sorry for the long time, but as nobody answered this until now, I will close the this and please if anybody has this error reopen with more information.
